description:
  artifact-name: springcloudconfigclient
  application-instance: production-instance
  remarks: This configuration is specific to the production instance of the spring application.
server:
  port: 2031
